name: Build & Deploy Django

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: echo "APP_NAME=${{ secrets.APP_NAME }}"

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.APP_NAME }} .

      # Login to CapRover Server
      - name: Login to CapRover
        run: |
          npm install -g caprover
          caprover login --caprover-url "${{ secrets.SERVER }}" --caprover-password "${{ secrets.APP_TOKEN }}"

      # Push Docker Image to CapRover
      - name: Push Image to CapRover
        run: |
          caprover deploy --caprover-app "${{ secrets.APP_NAME }}" --caprover-force-rebuild
