name: Build & Deploy Django

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install CapRover CLI
      - name: Install CapRover CLI
        run: npm install -g caprover

      # Deploy ke CapRover menggunakan CLI
      - name: Deploy App to CapRover
        run: |
          caprover deploy \
            --caprover-url "${{ secrets.SERVER }}" \
            --caprover-app "${{ secrets.APP_NAME }}" \
            --caprover-password "${{ secrets.APP_TOKEN }}"
