name: Build & Deploy Django

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t api-investbro .

      # Save the Docker Image as a tar file
      - name: Save Docker Image
        run: |
          docker save api-investbro -o deploy.tar

      # Deploy to CapRover
      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: "${{ secrets.SERVER }}"
          app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
          image: "api-investbro"
