name: Build & Deploy Django

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to CapRover Docker Registry
      - name: Log in to CapRover Docker Registry
        run: echo "${{ secrets.APP_TOKEN }}" | docker login ${{ secrets.SERVER }} -u captain --password-stdin

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.SERVER }}/captain/${{ secrets.APP_NAME }} .

      # Push Docker Image to CapRover
      - name: Push Docker Image
        run: docker push ${{ secrets.SERVER }}/captain/${{ secrets.APP_NAME }}

      # Deploy App in CapRover
      - name: Trigger Deployment in CapRover
        run: |
          curl -X POST "${{ secrets.SERVER }}/api/v2/user/apps/appData" \
            -H "x-namespace: captain" \
            -H "x-captain-auth: ${{ secrets.APP_TOKEN }}" \
            -d '{ "appName": "${{ secrets.APP_NAME }}", "newVersion": "latest" }'
